node:
  build: ./
  environment:
    - TERM=xterm
  volumes:
    - ./:/home/easysend
  links:
    - selenium

selenium:
  image: selenium/standalone-chrome-debug
  ports:
    - "4444:4444"
    - "5900:5900"
  volumes:
    - /dev/shm:/dev/shm
  environment:
    - TERM=xterm
